### PR TITLE
checkout and push to gh-pages branch

### PR DESCRIPTION
**Pull request by MariadeAnton**
checkout and push to gh-pages instead of master and avoid running into a loop

### CODE REVIEW

**Comment by Dorlige** [comment]
i have to make checkout and push to gh-pges in my file .sh?

**Comment by MariadeAnton** [comment]
@Dorlige where would you like to push?

at the moment, you're pushing to **master**, instead of **gh-pages**, causing the loop.

**Comment by Dorlige** [comment]
Now I pushed to gh-pages and I think the build is suspended.
Why is that?

**Comment by MariadeAnton** [comment]
Closing the PR since the changes have already been applied.

Thank you, @Dorlige!

**Comment by Dorlige** [comment]
Thank you

**Pull request closed without merging**
